import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  navy: "#0f172a",
  slate: "#334155",
  muted: "#64748b",
  line: "#dbeafe",
  cyan: "#22d3ee",
  pale: "#f8fafc",
  panel: "#e0f2fe",
};

export const styles = StyleSheet.create({
  page: { padding: "34 38 72 38", fontFamily: "Helvetica", fontSize: 9, color: colors.navy, lineHeight: 1.35 },
  header: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 18, borderBottom: `2 solid ${colors.cyan}`, marginBottom: 18 },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.navy, color: "#ffffff", fontFamily: "Helvetica-Bold", fontSize: 15, textAlign: "center", paddingTop: 10 },
  brandName: { fontFamily: "Helvetica-Bold", fontSize: 16 },
  legal: { color: colors.muted, fontSize: 8, marginTop: 2 },
  quoteTitle: { fontFamily: "Helvetica-Bold", fontSize: 24, textAlign: "right" },
  meta: { color: colors.slate, fontSize: 8, textAlign: "right" },
  badge: { alignSelf: "flex-end", marginTop: 4, padding: "3 7", backgroundColor: colors.panel, color: "#075985", fontFamily: "Helvetica-Bold", fontSize: 8, borderRadius: 8 },
  columns: { flexDirection: "row", gap: 14, marginBottom: 14 },
  card: { flex: 1, padding: 12, backgroundColor: colors.pale, border: `1 solid #e2e8f0`, borderRadius: 6 },
  section: { marginTop: 12, marginBottom: 4 },
  sectionTitle: { fontFamily: "Helvetica-Bold", color: colors.navy, fontSize: 12, marginBottom: 7 },
  label: { color: colors.muted, fontFamily: "Helvetica-Bold", fontSize: 8, textTransform: "uppercase", marginBottom: 3 },
  strong: { fontFamily: "Helvetica-Bold" },
  text: { color: colors.slate },
  small: { fontSize: 8, color: colors.muted },
  tableHeader: { flexDirection: "row", backgroundColor: colors.navy, color: "#ffffff", padding: "7 6", fontFamily: "Helvetica-Bold", fontSize: 8, borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  row: { flexDirection: "row", padding: "8 6", borderBottom: `1 solid #e2e8f0` },
  productCol: { width: "45%" },
  qtyCol: { width: "10%", textAlign: "right" },
  moneyCol: { width: "15%", textAlign: "right" },
  discountCol: { width: "15%", textAlign: "right" },
  totals: { marginTop: 12, marginLeft: "58%", padding: 10, border: `1 solid #cbd5e1`, borderRadius: 6 },
  totalRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 5 },
  payable: { marginTop: 4, paddingTop: 7, borderTop: `1 solid ${colors.navy}`, fontFamily: "Helvetica-Bold", fontSize: 12 },
  termGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  termCard: { width: "48%", padding: 10, backgroundColor: colors.pale, border: `1 solid #e2e8f0`, borderRadius: 6, marginBottom: 8 },
  footer: { position: "absolute", left: 38, right: 38, bottom: 22, paddingTop: 7, borderTop: `1 solid #cbd5e1`, color: colors.muted, fontSize: 7, textAlign: "center" },
  signatureRow: { flexDirection: "row", gap: 28, marginTop: 18 },
  signatureLine: { flex: 1, borderTop: `1 solid ${colors.muted}`, paddingTop: 4, color: colors.muted },
});
